---
- name: install | Adding MAAS Repo Info
  apt_repository:
    repo: '{{ maas_repo }}'
    state: "present"

- name: install | Installing MAAS (Single-Node)
  apt:
    name: "maas"
    state: "present"
  when: maas_single_node_install

- name: install | Installing maas-region-controller
  apt:
    name: "maas-region-controller"
    state: "present"
  when: >
        not maas_single_node_install and
        inventory_hostname in groups['maas_region_controller']

- name: install | Installing maas-rack-controller
  apt:
    name: "maas-rack-controller"
    state: "present"
  when: >
        not maas_single_node_install and
        inventory_hostname in groups['maas_rack_controller']

- name: install | Checking If MAAS Admin Account Has Been Created
  stat:
    path: "/etc/maas/.admin_account_created"
  register: "maas_admin_account_check"

- name: install | Creating MAAS Admin Account(s)
  command: "maas createadmin --username {{ item.username }} --email {{ item.email }} --password {{ item.password }}"
  register: "maas_admin_account_created"
  with_items: '{{ maas_adminusers }}'
  when: >
        (maas_single_node_install and
        not maas_admin_account_check.stat.exists) or
        (not maas_single_node_install and
          not maas_admin_account_check.stat.exists and
          inventory_hostname in groups['maas_region_controller'])

- name: install | Marking MAAS Admin Account As Being Created
  file:
    path: "/etc/maas/.admin_account_created"
    state: "touch"
  register: "maas_admin_added"
  when: maas_admin_account_created.changed

# Install libvirt-bin to control KVM instances
#- name: install | Installing Libvirt (KVM)
#  apt:
#    name: "libvirt-bin"
#    state: "present"

